#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Description: Ansible playbook to setup pre-requisites
# for the inbuilt NGINX loadbalancer.
#
# yamllint disable

---

- name: Deploy NGINX Loadbalancer on Master Nodes
  hosts: "{{hostlist}}"
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:

  - name: Open Port 6444
    firewalld:
      port: 6444/tcp
      permanent: yes
      state: enabled

  - name: Enable VRRP
    shell: |
           firewall-cmd --add-protocol=vrrp
           firewall-cmd --add-protocol=vrrp --permanent

  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted
      enabled: yes

  - name: Create NGINX systemd configuration directory
    file:
      path: /etc/systemd/system/olcne-nginx.service.d
      state: directory
    when:
    - use_proxy == true

  - name: Create NGINX Proxy File
    shell: |
            touch /etc/systemd/system/olcne-nginx.service.d/proxy.conf; echo "[Service]" >> /etc/systemd/system/olcne-nginx.service.d/proxy.conf; echo "Environment=\"HTTPS_PROXY={{ my_https_proxy }}\"" >> /etc/systemd/system/olcne-nginx.service.d/proxy.conf; echo "Environment=\"HTTP_PROXY={{ my_http_proxy }}\"" >> /etc/systemd/system/olcne-nginx.service.d/proxy.conf;echo "Environment=\"NO_PROXY={{ my_no_proxy }}\"" >> /etc/systemd/system/olcne-nginx.service.d/proxy.conf
    when:
    - use_proxy == true
