#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Description: Ansible playbook to setup certificates
# for OCNE API Server and OCNE Agent.
#
# yamllint disable

---

- name: Set up OCNE Certificates
  hosts: ocne_op
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:

  - name: Create X.509 Certificates and Copy to Nodes
    shell: |
           cd /etc/olcne
           /etc/olcne/gen-certs-helper.sh --cert-request-organization-unit "OCNE" --cert-request-organization "Oracle" --nodes {{ all_nodes }}
           cd /etc/olcne/configs/certificates/tmp-olcne/
           chmod 555 */node.key
           sed -i 's/^USER=opc/USER=root/' /etc/olcne/configs/certificates/olcne-tranfer-certs.sh
           bash -ex /etc/olcne/configs/certificates/olcne-tranfer-certs.sh
