#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Description: Ansible playbook to setup the OCNE Operator node.
#
# yamllint disable

---

- name: Provision OCNE cluster
  hosts: ocne_op
  gather_facts: true
  vars:
   - operator_str: "{{ansible_fqdn}}:8091"
   - proxy: "{{ use_proxy | default('false') }}"

  tasks:

  - name: Copy OCNE environment file to operator node when used
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/{{ env_file }}"
      dest: "~/{{ env_file }}"

  - name: Quick install with environment file
    command: olcnectl provision --ssh-identity-file ~/.ssh/k8s-key --yes --timeout 20 \
           --ssh-login-name "{{ ansible_user }}" \
           --config-file {{ env_file }}
    when:
      - proxy == false

  - name: Quick install with environment file and proxy enabled
    command: olcnectl provision --ssh-identity-file ~/.ssh/k8s-key --yes --timeout 20 \
           --ssh-login-name "{{ ansible_user }}" \
           --http-proxy  "{{ my_http_proxy }}" \
           --https-proxy "{{ my_https_proxy }}" \
           --no-proxy "{{ my_no_proxy }}" \
           --config-file {{ env_file }}
    when:
      - proxy == true

  - name: Update global flag configuration for environment 
    command: olcnectl module instances \ 
           --api-server {{ operator_str }} \ 
           --environment-name {{ ocne_environment }} \ 
           --update-config

- name: Set up kubectl on the Master Node
  hosts: ocne_kube_control
  gather_facts: false

  tasks:
  - name: Set up kubectl
    shell: |
            rm $HOME/.kube/config
            mkdir -p $HOME/.kube
            sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config
            echo 'export KUBECONFIG=$HOME/.kube/config' >> $HOME/.bashrc
