#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Oracle Linux Automation Manager Ansible playbook to list BTRFS snapshot and subvolume ID's
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# yamllint disable

---
- hosts: all
  become: yes

  tasks:
    - name: Gather uname output to determine if system is running Oracle Linux 8 UEK
      command: uname -r
      register: uname_contents

    - name: Fail if system is not running Oracle Linux 8 UEK
      fail:
        msg: System is not running Oracle Linux 8 UEK, we need to exit
      when: uname_contents.stdout.find('el8uek') == -1

    - name: Gather btrfs output for the root filesystem to determine if system if running btrfs
      command: stat -f --format="%T" /
      register: btrfs_contents

    - name: Fail if system is not using btrfs for the root filesystem
      fail:
        msg: System is not using btrfs for the root filesystem, we need to exit
      when: btrfs_contents.stdout.find('btrfs') == -1

    - name: Print out the btrfs subvolume for gathering the snapshot ID's
      command: btrfs subvolume list /
      register: btrfs_subvol_output

    - name: Print out the brtfs subvolumes for gathering the ID's
      debug:
        msg: "{{ item }}"
      loop: "{{ btrfs_subvol_output.stdout_lines }}"

    - name: Print out the current btrfs default subvolume id
      shell: btrfs subvolume get-default /
      register: btrfs_subvol_output

    - debug:
        msg: "Current btrfs default subvolume (current boot subvolume) details {{ btrfs_subvol_output.stdout_lines }}"
