#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Oracle Linux Automation Manager Ansible playbook to install & start HTTPD and configure an iptables based firewall
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# yamllint disable

---
- hosts: all
  become: yes
  tasks:
  - name: Gather aide state
    block:
      - name: Run aide check
        command: aide --check
        register: result
      - name: Report Aide OK
        debug:
          msg: AIDE found NO differences between database and filesystem. Looks okay!!
        when: result.rc == 0
    rescue:
      - name: Report Aide Error
        debug:
          msg: AIDE found differences between database and filesystem!!
      - name: Force a failure
        command: /bin/false
